language: swift
osx_image: xcode11.3
script:
- xcodebuild -project testLibrary.xcodeproj -scheme testLibrary -derivedDataPath Build/ -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 8' -enableCodeCoverage YES clean build test

